# fly.toml app configuration file generated for receipt-splitter on 2025-08-16
# This is the configuration for review apps.

[build]

[env]
  DEBUG = "False"
  DJANGO_SETTINGS_MODULE = "receipt_splitter.settings"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]


[processes]
  web = "gunicorn receipt_splitter.wsgi:application --bind 0.0.0.0:8000 --workers 1 --max-requests 100 --max-requests-jitter 25 --preload"

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"


[deploy]
  release_command = "python manage.py migrate --noinput"
