# Generated by Django 5.2.5 on 2025-08-16 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "prorated_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "prorated_tip",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("uploader_name", models.CharField(max_length=50)),
                ("restaurant_name", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tip", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="receipts/"),
                ),
                ("is_finalized", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claimer_name", models.CharField(max_length=50)),
                ("quantity_claimed", models.IntegerField(default=1)),
                ("session_id", models.CharField(max_length=100)),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                ("grace_period_ends", models.DateTimeField()),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="receipts.lineitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lineitem",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="receipts.receipt",
            ),
        ),
        migrations.CreateModel(
            name="ActiveViewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewer_name", models.CharField(max_length=50)),
                ("session_id", models.CharField(max_length=100)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewers",
                        to="receipts.receipt",
                    ),
                ),
            ],
            options={
                "unique_together": {("receipt", "session_id")},
            },
        ),
    ]
