# Generated by Django 5.2.5 on 2025-08-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0002_receipt_processing_error_receipt_processing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="prorated_tax",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="prorated_tip",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="total_price",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="subtotal",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="tax",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="tip",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="total",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
