# Generated by Django 5.2.5 on 2025-08-16 15:59

from django.db import migrations, models
import random
import string


def generate_slugs_for_existing_receipts(apps, schema_editor):
    """Generate unique slugs for all existing receipts."""
    Receipt = apps.get_model('receipts', 'Receipt')
    chars = string.ascii_lowercase + string.digits
    
    for receipt in Receipt.objects.all():
        # Generate a unique slug
        max_attempts = 100
        for attempt in range(max_attempts):
            slug = ''.join(random.choice(chars) for _ in range(6))
            if not Receipt.objects.filter(slug=slug).exists():
                receipt.slug = slug
                receipt.save(update_fields=['slug'])
                break
        else:
            # If we couldn't generate a unique 6-char slug, try longer ones
            for extra_length in range(1, 4):
                slug = ''.join(random.choice(chars) for _ in range(6 + extra_length))
                if not Receipt.objects.filter(slug=slug).exists():
                    receipt.slug = slug
                    receipt.save(update_fields=['slug'])
                    break


def reverse_slug_generation(apps, schema_editor):
    """Remove slugs from all receipts (for migration reversal)."""
    Receipt = apps.get_model('receipts', 'Receipt')
    Receipt.objects.update(slug='')


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0003_increase_decimal_precision"),
    ]

    operations = [
        # First, add the field without unique constraint
        migrations.AddField(
            model_name="receipt",
            name="slug",
            field=models.CharField(
                blank=True, db_index=True, max_length=10, default=''
            ),
        ),
        # Generate slugs for existing receipts
        migrations.RunPython(
            generate_slugs_for_existing_receipts,
            reverse_slug_generation
        ),
        # Now alter the field to add unique constraint
        migrations.AlterField(
            model_name="receipt",
            name="slug",
            field=models.CharField(
                blank=True, db_index=True, max_length=10, unique=True
            ),
        ),
    ]