# Generated by Django 5.2.5 on 2025-08-16 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0004_receipt_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="image",
        ),
    ]
