# Generated by Django 5.2.5 on 2025-08-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_remove_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='grace_period_ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
