# Generated by Django 5.2.5 on 2025-08-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_claim_finalized_at_claim_is_finalized_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activeviewer',
            index=models.Index(fields=['session_id'], name='receipts_ac_session_09ae39_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['session_id'], name='receipts_cl_session_25523b_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claimer_name'], name='receipts_cl_claimer_5fa59e_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['line_item', 'session_id'], name='receipts_cl_line_it_9f385c_idx'),
        ),
    ]
