# Generated by Django 5.2.5 on 2025-09-18 02:41

from django.db import migrations, models

def copy_quantities(apps, schema_editor):
    LineItem = apps.get_model('receipts', 'LineItem')
    for item in LineItem.objects.all():
        item.quantity_numerator = item.quantity
        item.save(update_fields=['quantity_numerator'])

    Claim = apps.get_model('receipts', 'Claim')
    for claim in Claim.objects.all():
        claim.quantity_numerator = claim.quantity_claimed
        claim.save(update_fields=['quantity_numerator'])

class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0007_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="quantity_denominator",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="claim",
            name="quantity_numerator",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="quantity_denominator",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="quantity_numerator",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(copy_quantities),
    ]
