# Generated by Django 5.2.5 on 2026-02-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0009_shared_denominator_and_venmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeviewer',
            name='venmo_username',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
