# Generated by Django 5.2.5 on 2026-08-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0012_unescape_legacy_html_entities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeviewer',
            name='venmo_username',
        ),
    ]
